# Configuration for Transformer Model Experiment

data:
  directory: "data/battery" # As in original script
  # Features are derived after preprocessing in this script's logic
  features: ['pack_voltage (V)', 'charge_current (A)', 'max_cell_voltage (V)', 'min_cell_voltage (V)', 'max_temperature (C)', 'min_temperature (C)', 'available_energy (Wh)'] # Example, needs to match output of new preprocessor
  targets: ['available_capacity (Ah)']
  seq_len: 30
  train_split_ratio: 0.7  # As in original script
  val_split_ratio: 0.15 # As in original script
  # Preprocessing steps specific to this data might need separate config or handling
  preprocessing:
    type: 'battery_transformer_style' # Flag for specific preprocessing
    voltage_col: 'pack_voltage (V)'
    current_col: 'charge_current (A)'
    timestamp_col: 'timestamp'
    target_col: 'available_capacity (Ah)'
    window_size_hours: 5
    sampling_rate_hz: 0.016666666666666666 # 1/60
    downsample_freq: '15T'
    filter_type: 'butterworth'
    remove_negatives: true
    normalize: true

model:
  type: 'transformer'
  params:
    embed_dim: 256
    num_blocks: 4 # Example, adjust based on SOHTransformer
    num_heads: 16 # Example, adjust based on SOHTransformer
    ffn_dim: 1024 # Example, adjust based on SOHTransformer
    drop_path_rate: 0.1 # Example, adjust based on SOHTransformer
    output_dim: 30 # Should match seq_len for Transformer in utils.py

training:
  batch_size: 32
  num_epochs: 50
  learning_rate: 0.00005
  weight_decay: 0.0001
  use_gpu: true

evaluation:
  plot_figure: true

monitoring:
  enable: true
  idle_duration: 1
  train_interval: 1
  test_interval: 0.01

outputs:
  logs_dir: "outputs/logs"
  models_dir: "outputs/models"
  figures_dir: "outputs/figures"
